### PR TITLE
Simplify root filesystem

### PR DESCRIPTION
**Pull request by razvand**
Remove `bin/`, `include/`, `lib/test/` and `pyenv.cfg` from the root filesystem archive (`rootfs.tar.gz`). These are not required by Python applications:

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
@razvand change the `:` at the end of the commit message to a `.`. All good besides that.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by andreittr** [comment]
Removing the `bin/` directory is technically fine for running python apps, however it removes the ability for a user to customize this rootfs/virtualenv further with pip (you need `bin/activate` to enter the venv and customize it). Is this what we intend? If so, it's OK, we just tell users to build their own rootfs if they want customization.

edit: actually, having users build their own rootfs is probably preferable, as the activate script seems to hardcode the absolute path to the venv, so I'm not sure how well it would perform if moved :/ I have to think this issue through a bit and patch the rootfs build code, but this change is a-ok (modulo the commit message change as mentioned by @StefanJum ).

Reviewed-by: Andrei Tatar <andrei@unikraft.io>

**Comment by razvand** [comment]
@StefanJum , @andreittr , made the updates.

@andreittr , after @StefanJum reviews the PR, you should approve it, you're the assignee.

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by andreittr** [comment]
Approved-by: Andrei Tatar <andrei@unikraft.io>

**Pull request closed without merging**
