### PR TITLE
Fix rootfs mistakenly containing numpy

### PR DESCRIPTION
**Pull request by andreittr**
`rootfs.tar.gz` previolusly mistakenly contained python files for numpy; these are now removed.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by RaduNichita — APPROVED** [review]
All good from my side. 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
Tested and it works, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
