### PR TITLE
Update default Python app to 3.10.11

### PR DESCRIPTION
**Pull request by andreittr**
Update the prebuilt Python rootfs to 3.10.11, containing a minimal standard library without extensions.

In addition, update the README and Makefile.

Part of the larger Python 3.10 work:
- https://github.com/unikraft/lib-python3/pull/15

### CODE REVIEW

**Comment by StefanJum** [comment]
@andreittr can you please also update the `Makefile` to add all the [library dependencies](https://github.com/unikraft/lib-python3/pull/15#issue-1821079952)?

**Comment by andreittr** [comment]
> @andreittr can you please also update the `Makefile` to add all the [library dependencies](https://github.com/unikraft/lib-python3/pull/15#issue-1821079952)?

From what I can tell this app intends to build a minimal Python 3 without any extensions (the configs and Makefile reflect this), and for that reason the Makefile is perfectly adequate. The long list of libs mentioned in the PR is for when you want to build py3 with all possible extensions; they are not dependencies and python builds perfectly well without them.

**Comment by StefanJum** [comment]
> From what I can tell this app intends to build a minimal Python 3 without any extensions (the configs and Makefile reflect this).

Yes, that should be it, but I get some errors if I only leave the current libraries:
```
workdir/apps/python3/build/libpython3/origin/Python-3.10.11/Include/internal/pycore_bitutils.h:101: undefined reference to `__popcountdi2'
```

**Comment by andreittr** [comment]
> > From what I can tell this app intends to build a minimal Python 3 without any extensions (the configs and Makefile reflect this).
> 
> Yes, that should be it, but I get some errors if I only leave the current libraries:
> 
> ```
> workdir/apps/python3/build/libpython3/origin/Python-3.10.11/Include/internal/pycore_bitutils.h:101: undefined reference to `__popcountdi2'
> ```

Hmm, `__popcountdi2` seems to be defined by libcompiler-rt; what compiler & version are you using? (if it's common enough we might need to pull in libcompiler-rt just to be safe).

Edit: nvm, it seems to fail w/ gcc 13 (but not clang), so best to pull in compiler-rt (lib-python3 already implies it). Commit incoming.

**Comment by StefanJum** [comment]
> Hmm, `__popcountdi2` seems to be defined by libcompiler-rt; what compiler & version are you using? (if it's common enough we might need to pull in libcompiler-rt just to be safe).

`gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~23.04) ` yes, we should pull `compiler-rt`

**Comment by StefanJum** [comment]
@andreittr please update `libuuid` to `compiler-rt` in the other places in the README:

* https://github.com/unikraft/app-python3/blob/staging/README.md?plain=1#L98
* https://github.com/unikraft/app-python3/blob/staging/README.md?plain=1#L163
* https://github.com/unikraft/app-python3/blob/staging/README.md?plain=1#L186

**Comment by andreittr** [comment]
> @andreittr please update `libuuid` to `compiler-rt` in the other places in the README:
> 
>     * https://github.com/unikraft/app-python3/blob/staging/README.md?plain=1#L98
> 
>     * https://github.com/unikraft/app-python3/blob/staging/README.md?plain=1#L163
> 
>     * https://github.com/unikraft/app-python3/blob/staging/README.md?plain=1#L186

Whoops, my bad, fixed now.

**Review by StefanJum — APPROVED** [review]
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
Thanks, all good!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
