### PR TITLE
Add KraftKit configuration file for KraftCloud

### PR DESCRIPTION
**Pull request by razvand**
Add `kraft.cloud.yaml` configuration file to build and run for KraftCloud.

Build with:

```console
kraft build --kraftfile kraft.cloud.yaml -j $(nproc)
```

Run with:

```console
kraft run --kraftfile kraft.cloud.yaml --plat firecracker --initrd ./fs0 -- /helloworld.py
```

### CODE REVIEW

**Review by StefanJum — CHANGES_REQUESTED** [review]
Should we add `compiler-rt` to the libraries list?
Without it I get some undefined references to `__popcountdi2`.

**Review by marcrittinghaus — APPROVED** [review]
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Comment by craciunoiuc** [comment]
> Should we add `compiler-rt` to the libraries list? Without it I get some undefined references to `__popcountdi2`.

I also had this, so I guess it's a dependency, @razvand will you add it?

**Comment by razvand** [comment]
> > Should we add `compiler-rt` to the libraries list? Without it I get some undefined references to `__popcountdi2`.
> 
> I also had this, so I guess it's a dependency, @razvand will you add it?

Yes, I'll have to test it.

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Pull request closed without merging**
